//
//  BranchFacilityIcon.m
//  auroraride
//
//  Created by liasica on 2023/12/29.
//  Copyright © 2023 auroraride. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import "BranchFacilityIcon.h"

#define UIColorFromRGB(rgbValue) [UIColor colorWithRed:((float)((rgbValue & 0xFF0000) >> 16))/255.0 green:((float)((rgbValue & 0xFF00) >> 8))/255.0 blue:((float)(rgbValue & 0xFF))/255.0 alpha:1.0]

@implementation BranchFacilityIcon

/// 门店设施 - 非驿站
NSString * const BranchFacilityTypeStore = @"store";

/// 门店设施 - 驿站
NSString * const BranchFacilityTypeRest = @"rest";

/// 72V电柜设施
NSString * const BranchFacilityTypeV72 = @"v72";

/// 60V电柜设施
NSString * const BranchFacilityTypeV60 = @"v60";

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

/// 参考
/// 添加自定义字体 https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/
/// https://stackoverflow.com/questions/35919795/objective-c-draw-an-image
/// https://www.jianshu.com/p/77a5dbed7da2
/// https://stackoverflow.com/a/5866619/4160831
/// https://stackoverflow.com/a/6823536/4160831
/// https://stackoverflow.com/a/9829205/4160831
/// Core Graphic 使用 https://tbfungeek.github.io/2019/08/06/Core-graphic-%E4%BD%BF%E7%94%A8/index.html
/// https://juejin.cn/post/6894530597851496455
/// https://www.cnblogs.com/HypeCheng/articles/4159049.html
/// https://furnacedigital.blogspot.com/2010/12/quartz-2d.html
+ (UIImage *) draw:(int)number scale:(double)scale branchFacilityType:(NSString *)branchFacilityType color:(NSString *)color
{
    double width = DESIGISIZE.width * scale;
    double height = DESIGISIZE.height * scale;
    
    UIColor *iconColor = [self UIColorFromHexString:color];
    
    CGSize size = CGSizeMake(width, height);
    
    // 1.开启图形上下文，并将ImageContext放置到栈顶
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    
    // 2.绘制图形（电柜设施）
    [self drawBranchFacilityIconWithFrame: CGRectMake(0, 0, width, height) number:number branchFacilityType:branchFacilityType resizing: BranchFacilityIconResizingBehaviorStretch iconColor:iconColor];
    
    // 3.从上下文中获取图片
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    
    // 4.关闭图形上下文
    UIGraphicsEndImageContext();
    
    return image;
}

#pragma mark 网点设施图标绘制
+ (void)drawBranchFacilityIconWithFrame: (CGRect)targetFrame number:(int)number branchFacilityType:(NSString *)branchFacilityType resizing:(BranchFacilityIconResizingBehavior)resizing iconColor:(UIColor *)iconColor
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //// Resize to Target Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = BranchFacilityIconResizingBehaviorApply(resizing, CGRectMake(0, 0, 90, 104), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 90, resizedFrame.size.height / 104);
    CGFloat resizedShadowScale = MIN(resizedFrame.size.width / 90, resizedFrame.size.height / 104);
    
    //// Color Declarations
    UIColor* wrapperColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* ovalColor = [UIColor colorWithRed: 0.18 green: 0.208 blue: 0.247 alpha: 1];
    UIColor* shadowColor = [UIColor colorWithRed: 0.063 green: 0.114 blue: 0.204 alpha: 0.063];
    
    //// Shadow Declarations
    NSShadow* shadow = [[NSShadow alloc] init];
    shadow.shadowColor = shadowColor;
    shadow.shadowOffset = CGSizeMake(0, 4);
    shadow.shadowBlurRadius = 8;
    
    //// IconGroup
    //// Bezier Drawing
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(71.16, 14.68)];
    [bezierPath addCurveToPoint: CGPointMake(18.84, 14.68) controlPoint1: CGPointMake(56.72, 0.44) controlPoint2: CGPointMake(33.28, 0.44)];
    [bezierPath addCurveToPoint: CGPointMake(12.88, 58.56) controlPoint1: CGPointMake(6.77, 26.57) controlPoint2: CGPointMake(4.78, 44.64)];
    [bezierPath addCurveToPoint: CGPointMake(18.84, 66.23) controlPoint1: CGPointMake(14.47, 61.3) controlPoint2: CGPointMake(16.46, 63.88)];
    [bezierPath addLineToPoint: CGPointMake(45, 92)];
    [bezierPath addLineToPoint: CGPointMake(71.16, 66.23)];
    [bezierPath addCurveToPoint: CGPointMake(77.12, 58.56) controlPoint1: CGPointMake(73.54, 63.88) controlPoint2: CGPointMake(75.53, 61.3)];
    [bezierPath addCurveToPoint: CGPointMake(71.16, 14.68) controlPoint1: CGPointMake(85.22, 44.64) controlPoint2: CGPointMake(83.23, 26.57)];
    [bezierPath closePath];
    CGContextSaveGState(context);
    CGContextSetShadowWithColor(context,
                                CGSizeMake(shadow.shadowOffset.width * resizedShadowScale, shadow.shadowOffset.height * resizedShadowScale),
                                shadow.shadowBlurRadius * resizedShadowScale,
                                [shadow.shadowColor CGColor]);
    [wrapperColor setFill];
    [bezierPath fill];
    CGContextRestoreGState(context);
    
    
    //// Circle Drawing
    UIBezierPath* circlePath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(12, 8, 66, 66)];
    [iconColor setFill];
    [circlePath fill];
    
    
#pragma mark 电柜绘制
    if ([[branchFacilityType lowercaseString] isEqual:BranchFacilityTypeV72] || [[branchFacilityType lowercaseString] isEqual:BranchFacilityTypeV60]) {
        //Oval Drawing
        UIBezierPath* ovalPath = [UIBezierPath bezierPath];
        [ovalPath moveToPoint: CGPointMake(75.16, 54.4)];
        [ovalPath addCurveToPoint: CGPointMake(45, 74) controlPoint1: CGPointMake(70.02, 65.95) controlPoint2: CGPointMake(58.45, 74)];
        [ovalPath addCurveToPoint: CGPointMake(14.84, 54.4) controlPoint1: CGPointMake(31.55, 74) controlPoint2: CGPointMake(19.98, 65.95)];
        [ovalPath addCurveToPoint: CGPointMake(45, 50) controlPoint1: CGPointMake(23.54, 51.62) controlPoint2: CGPointMake(33.89, 50)];
        [ovalPath addCurveToPoint: CGPointMake(75.16, 54.4) controlPoint1: CGPointMake(56.11, 50) controlPoint2: CGPointMake(66.46, 51.62)];
        [ovalPath closePath];
        [ovalColor setFill];
        [ovalPath fill];
        
        //// Battery Model Drawing
        CGRect branchFacilityTypeRect = CGRectMake(27, 56, 36, 14);
        {
            NSString* textContent = @"72V";
            if ([[branchFacilityType lowercaseString] isEqual:BranchFacilityTypeV60]) {
                textContent = @"60V";
            }
            
            NSMutableParagraphStyle* branchFacilityTypeStyle = [[NSMutableParagraphStyle alloc] init];
            branchFacilityTypeStyle.alignment = NSTextAlignmentCenter;
            NSDictionary* branchFacilityTypeFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"LucidaGrande" size: 16], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: branchFacilityTypeStyle};
            
            CGFloat branchFacilityTypeTextHeight = [textContent boundingRectWithSize: CGSizeMake(branchFacilityTypeRect.size.width, INFINITY) options: NSStringDrawingUsesLineFragmentOrigin attributes: branchFacilityTypeFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, branchFacilityTypeRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(branchFacilityTypeRect), CGRectGetMinY(branchFacilityTypeRect) + (branchFacilityTypeRect.size.height - branchFacilityTypeTextHeight) / 2, branchFacilityTypeRect.size.width, branchFacilityTypeTextHeight) withAttributes: branchFacilityTypeFontAttributes];
            CGContextRestoreGState(context);
        }
        
        
        //// Number Drawing
        CGRect numberRect = CGRectMake(12, 14, 66, 36);
        {
            NSString* textContent = [NSString stringWithFormat:@"%d", number];
            NSMutableParagraphStyle* numberStyle = [[NSMutableParagraphStyle alloc] init];
            numberStyle.alignment = NSTextAlignmentCenter;
            NSDictionary* numberFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"LucidaGrande" size: 30], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: numberStyle};
            
            CGFloat numberTextHeight = [textContent boundingRectWithSize: CGSizeMake(numberRect.size.width, INFINITY) options: NSStringDrawingUsesLineFragmentOrigin attributes: numberFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, numberRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(numberRect), CGRectGetMinY(numberRect) + (numberRect.size.height - numberTextHeight) / 2, numberRect.size.width, numberTextHeight) withAttributes: numberFontAttributes];
            CGContextRestoreGState(context);
        }
        
    }
    
#pragma mark 驿站绘制
    if ([[branchFacilityType lowercaseString] isEqual:BranchFacilityTypeRest]) {
        UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
        [bezier3Path moveToPoint: CGPointMake(45, 29)];
        [bezier3Path addLineToPoint: CGPointMake(60.7, 42.66)];
        [bezier3Path addLineToPoint: CGPointMake(60.7, 56.7)];
        [bezier3Path addCurveToPoint: CGPointMake(57.56, 59.84) controlPoint1: CGPointMake(60.7, 58.27) controlPoint2: CGPointMake(59.13, 59.84)];
        [bezier3Path addLineToPoint: CGPointMake(32.44, 59.84)];
        [bezier3Path addCurveToPoint: CGPointMake(29.3, 56.7) controlPoint1: CGPointMake(30.87, 59.84) controlPoint2: CGPointMake(29.3, 58.27)];
        [bezier3Path addLineToPoint: CGPointMake(29.3, 42.66)];
        [bezier3Path addLineToPoint: CGPointMake(45, 29)];
        [bezier3Path closePath];
        [bezier3Path moveToPoint: CGPointMake(46.57, 44.14)];
        [bezier3Path addLineToPoint: CGPointMake(43.43, 44.14)];
        [bezier3Path addCurveToPoint: CGPointMake(40.29, 47.28) controlPoint1: CGPointMake(41.7, 44.14) controlPoint2: CGPointMake(40.29, 45.55)];
        [bezier3Path addLineToPoint: CGPointMake(40.29, 55.13)];
        [bezier3Path addLineToPoint: CGPointMake(49.71, 55.13)];
        [bezier3Path addLineToPoint: CGPointMake(49.71, 47.28)];
        [bezier3Path addCurveToPoint: CGPointMake(46.57, 44.14) controlPoint1: CGPointMake(49.71, 45.55) controlPoint2: CGPointMake(48.3, 44.14)];
        [bezier3Path closePath];
        [bezier3Path moveToPoint: CGPointMake(45, 22.16)];
        [bezier3Path addCurveToPoint: CGPointMake(47.28, 23) controlPoint1: CGPointMake(45.82, 22.16) controlPoint2: CGPointMake(46.63, 22.44)];
        [bezier3Path addLineToPoint: CGPointMake(52.85, 27.85)];
        [bezier3Path addLineToPoint: CGPointMake(52.85, 25.3)];
        [bezier3Path addCurveToPoint: CGPointMake(54.42, 23.73) controlPoint1: CGPointMake(52.85, 24.43) controlPoint2: CGPointMake(53.55, 23.73)];
        [bezier3Path addLineToPoint: CGPointMake(55.99, 23.73)];
        [bezier3Path addCurveToPoint: CGPointMake(57.56, 25.3) controlPoint1: CGPointMake(56.86, 23.73) controlPoint2: CGPointMake(57.56, 24.43)];
        [bezier3Path addLineToPoint: CGPointMake(57.56, 31.95)];
        [bezier3Path addLineToPoint: CGPointMake(66.41, 39.66)];
        [bezier3Path addCurveToPoint: CGPointMake(66.88, 41.49) controlPoint1: CGPointMake(66.93, 40.11) controlPoint2: CGPointMake(67.12, 40.84)];
        [bezier3Path addCurveToPoint: CGPointMake(65.35, 42.57) controlPoint1: CGPointMake(66.64, 42.14) controlPoint2: CGPointMake(66.03, 42.57)];
        [bezier3Path addLineToPoint: CGPointMake(62.99, 42.57)];
        [bezier3Path addLineToPoint: CGPointMake(45, 26.92)];
        [bezier3Path addLineToPoint: CGPointMake(27.01, 42.57)];
        [bezier3Path addLineToPoint: CGPointMake(24.65, 42.57)];
        [bezier3Path addCurveToPoint: CGPointMake(23.12, 41.49) controlPoint1: CGPointMake(23.97, 42.57) controlPoint2: CGPointMake(23.36, 42.14)];
        [bezier3Path addCurveToPoint: CGPointMake(23.59, 39.66) controlPoint1: CGPointMake(22.88, 40.84) controlPoint2: CGPointMake(23.07, 40.11)];
        [bezier3Path addLineToPoint: CGPointMake(42.72, 23)];
        [bezier3Path addCurveToPoint: CGPointMake(45, 22.16) controlPoint1: CGPointMake(43.37, 22.44) controlPoint2: CGPointMake(44.18, 22.16)];
        [bezier3Path closePath];
        bezier3Path.usesEvenOddFillRule = YES;
        [[UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1] setFill];
        [bezier3Path fill];
    }
    
#pragma mark 门店绘制
    if ([[branchFacilityType lowercaseString] isEqual:BranchFacilityTypeStore]) {
        UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
        [bezier3Path moveToPoint: CGPointMake(55, 40.3)];
        [bezier3Path addCurveToPoint: CGPointMake(55.85, 41.2) controlPoint1: CGPointMake(55.24, 40.62) controlPoint2: CGPointMake(55.53, 40.92)];
        [bezier3Path addCurveToPoint: CGPointMake(60, 42.65) controlPoint1: CGPointMake(56.97, 42.14) controlPoint2: CGPointMake(58.44, 42.65)];
        [bezier3Path addCurveToPoint: CGPointMake(61.99, 42.36) controlPoint1: CGPointMake(60.69, 42.65) controlPoint2: CGPointMake(61.36, 42.55)];
        [bezier3Path addLineToPoint: CGPointMake(61.99, 56.3)];
        [bezier3Path addCurveToPoint: CGPointMake(58.33, 60) controlPoint1: CGPointMake(61.99, 58.35) controlPoint2: CGPointMake(60.35, 60)];
        [bezier3Path addLineToPoint: CGPointMake(31.67, 60)];
        [bezier3Path addCurveToPoint: CGPointMake(28.01, 56.3) controlPoint1: CGPointMake(29.65, 60) controlPoint2: CGPointMake(28.01, 58.35)];
        [bezier3Path addLineToPoint: CGPointMake(28.01, 42.36)];
        [bezier3Path addCurveToPoint: CGPointMake(30, 42.65) controlPoint1: CGPointMake(28.64, 42.55) controlPoint2: CGPointMake(29.31, 42.65)];
        [bezier3Path addCurveToPoint: CGPointMake(34.14, 41.2) controlPoint1: CGPointMake(31.56, 42.65) controlPoint2: CGPointMake(33.03, 42.14)];
        [bezier3Path addCurveToPoint: CGPointMake(35, 40.3) controlPoint1: CGPointMake(34.47, 40.92) controlPoint2: CGPointMake(34.76, 40.62)];
        [bezier3Path addCurveToPoint: CGPointMake(35.85, 41.2) controlPoint1: CGPointMake(35.24, 40.62) controlPoint2: CGPointMake(35.53, 40.92)];
        [bezier3Path addCurveToPoint: CGPointMake(40, 42.65) controlPoint1: CGPointMake(36.97, 42.14) controlPoint2: CGPointMake(38.44, 42.65)];
        [bezier3Path addCurveToPoint: CGPointMake(44.14, 41.2) controlPoint1: CGPointMake(41.56, 42.65) controlPoint2: CGPointMake(43.03, 42.14)];
        [bezier3Path addCurveToPoint: CGPointMake(45, 40.3) controlPoint1: CGPointMake(44.47, 40.92) controlPoint2: CGPointMake(44.76, 40.62)];
        [bezier3Path addCurveToPoint: CGPointMake(45.85, 41.2) controlPoint1: CGPointMake(45.24, 40.62) controlPoint2: CGPointMake(45.53, 40.92)];
        [bezier3Path addCurveToPoint: CGPointMake(50, 42.65) controlPoint1: CGPointMake(46.97, 42.14) controlPoint2: CGPointMake(48.44, 42.65)];
        [bezier3Path addCurveToPoint: CGPointMake(54.14, 41.2) controlPoint1: CGPointMake(51.56, 42.65) controlPoint2: CGPointMake(53.03, 42.14)];
        [bezier3Path addCurveToPoint: CGPointMake(55, 40.3) controlPoint1: CGPointMake(54.47, 40.92) controlPoint2: CGPointMake(54.76, 40.62)];
        [bezier3Path closePath];
        [bezier3Path moveToPoint: CGPointMake(39.38, 44.31)];
        [bezier3Path addCurveToPoint: CGPointMake(38.04, 45.26) controlPoint1: CGPointMake(38.92, 44.39) controlPoint2: CGPointMake(38.36, 44.73)];
        [bezier3Path addLineToPoint: CGPointMake(40.36, 46.73)];
        [bezier3Path addLineToPoint: CGPointMake(40.46, 48.67)];
        [bezier3Path addLineToPoint: CGPointMake(38.69, 49.43)];
        [bezier3Path addLineToPoint: CGPointMake(36.37, 47.96)];
        [bezier3Path addCurveToPoint: CGPointMake(36.11, 49.59) controlPoint1: CGPointMake(36, 48.55) controlPoint2: CGPointMake(35.98, 49.17)];
        [bezier3Path addCurveToPoint: CGPointMake(37.67, 51.53) controlPoint1: CGPointMake(36.24, 50.03) controlPoint2: CGPointMake(36.59, 50.85)];
        [bezier3Path addCurveToPoint: CGPointMake(41.62, 51.46) controlPoint1: CGPointMake(38.76, 52.21) controlPoint2: CGPointMake(40.57, 52.36)];
        [bezier3Path addCurveToPoint: CGPointMake(42.35, 51.39) controlPoint1: CGPointMake(41.77, 51.33) controlPoint2: CGPointMake(42, 51.18)];
        [bezier3Path addCurveToPoint: CGPointMake(50.78, 57.07) controlPoint1: CGPointMake(42.74, 51.63) controlPoint2: CGPointMake(50.78, 57.07)];
        [bezier3Path addCurveToPoint: CGPointMake(52.98, 56.57) controlPoint1: CGPointMake(51.49, 57.59) controlPoint2: CGPointMake(52.51, 57.31)];
        [bezier3Path addCurveToPoint: CGPointMake(52.47, 54.36) controlPoint1: CGPointMake(53.44, 55.82) controlPoint2: CGPointMake(53.25, 54.77)];
        [bezier3Path addCurveToPoint: CGPointMake(48.35, 51.93) controlPoint1: CGPointMake(52.47, 54.36) controlPoint2: CGPointMake(50.45, 53.17)];
        [bezier3Path addLineToPoint: CGPointMake(47.82, 51.62)];
        [bezier3Path addCurveToPoint: CGPointMake(43.72, 49.19) controlPoint1: CGPointMake(45.81, 50.43) controlPoint2: CGPointMake(43.87, 49.28)];
        [bezier3Path addCurveToPoint: CGPointMake(43.46, 48.49) controlPoint1: CGPointMake(43.39, 48.98) controlPoint2: CGPointMake(43.42, 48.71)];
        [bezier3Path addCurveToPoint: CGPointMake(41.78, 44.89) controlPoint1: CGPointMake(43.77, 46.74) controlPoint2: CGPointMake(42.68, 45.49)];
        [bezier3Path addCurveToPoint: CGPointMake(39.38, 44.31) controlPoint1: CGPointMake(40.85, 44.26) controlPoint2: CGPointMake(39.83, 44.23)];
        [bezier3Path closePath];
        [bezier3Path moveToPoint: CGPointMake(51.87, 55.21)];
        [bezier3Path addCurveToPoint: CGPointMake(52.04, 55.97) controlPoint1: CGPointMake(52.12, 55.37) controlPoint2: CGPointMake(52.2, 55.71)];
        [bezier3Path addCurveToPoint: CGPointMake(51.28, 56.15) controlPoint1: CGPointMake(51.88, 56.23) controlPoint2: CGPointMake(51.54, 56.31)];
        [bezier3Path addCurveToPoint: CGPointMake(51.11, 55.38) controlPoint1: CGPointMake(51.03, 55.99) controlPoint2: CGPointMake(50.95, 55.64)];
        [bezier3Path addCurveToPoint: CGPointMake(51.87, 55.21) controlPoint1: CGPointMake(51.27, 55.13) controlPoint2: CGPointMake(51.61, 55.05)];
        [bezier3Path closePath];
        [bezier3Path moveToPoint: CGPointMake(59.89, 25)];
        [bezier3Path addCurveToPoint: CGPointMake(61.87, 26.61) controlPoint1: CGPointMake(60.79, 25) controlPoint2: CGPointMake(61.58, 25.65)];
        [bezier3Path addLineToPoint: CGPointMake(65, 37.08)];
        [bezier3Path addCurveToPoint: CGPointMake(60, 41.29) controlPoint1: CGPointMake(65, 39.41) controlPoint2: CGPointMake(62.76, 41.29)];
        [bezier3Path addCurveToPoint: CGPointMake(55, 37.08) controlPoint1: CGPointMake(57.24, 41.29) controlPoint2: CGPointMake(55, 39.41)];
        [bezier3Path addCurveToPoint: CGPointMake(50, 41.29) controlPoint1: CGPointMake(55, 39.41) controlPoint2: CGPointMake(52.76, 41.29)];
        [bezier3Path addCurveToPoint: CGPointMake(45, 37.08) controlPoint1: CGPointMake(47.24, 41.29) controlPoint2: CGPointMake(45, 39.41)];
        [bezier3Path addCurveToPoint: CGPointMake(40, 41.29) controlPoint1: CGPointMake(45, 39.41) controlPoint2: CGPointMake(42.76, 41.29)];
        [bezier3Path addCurveToPoint: CGPointMake(35, 37.08) controlPoint1: CGPointMake(37.24, 41.29) controlPoint2: CGPointMake(35, 39.41)];
        [bezier3Path addCurveToPoint: CGPointMake(30, 41.29) controlPoint1: CGPointMake(35, 39.41) controlPoint2: CGPointMake(32.76, 41.29)];
        [bezier3Path addCurveToPoint: CGPointMake(25, 37.08) controlPoint1: CGPointMake(27.24, 41.29) controlPoint2: CGPointMake(25, 39.41)];
        [bezier3Path addLineToPoint: CGPointMake(28.13, 26.61)];
        [bezier3Path addCurveToPoint: CGPointMake(30.11, 25) controlPoint1: CGPointMake(28.41, 25.65) controlPoint2: CGPointMake(29.21, 25)];
        [bezier3Path addLineToPoint: CGPointMake(59.89, 25)];
        [bezier3Path closePath];
        [[UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1] setFill];
        [bezier3Path fill];
    }
    
    
    CGContextRestoreGState(context);
}


+ (UIColor *)UIColorFromHexString:(NSString *)hexString {
    unsigned rgbValue = 0;
    NSScanner *scanner = [NSScanner scannerWithString:hexString];
    [scanner setScanLocation:1]; // bypass '#' character
    [scanner scanHexInt:&rgbValue];
    return [UIColor colorWithRed:((rgbValue & 0xFF0000) >> 16)/255.0 green:((rgbValue & 0xFF00) >> 8)/255.0 blue:(rgbValue & 0xFF)/255.0 alpha:1.0];
}

@end



CGRect BranchFacilityIconResizingBehaviorApply(BranchFacilityIconResizingBehavior behavior, CGRect rect, CGRect target)
{
    if (CGRectEqualToRect(rect, target) || CGRectEqualToRect(target, CGRectZero))
        return rect;
    
    CGSize scales = CGSizeZero;
    scales.width = ABS(target.size.width / rect.size.width);
    scales.height = ABS(target.size.height / rect.size.height);
    
    switch (behavior)
    {
        case BranchFacilityIconResizingBehaviorAspectFit:
        {
            scales.width = MIN(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case BranchFacilityIconResizingBehaviorAspectFill:
        {
            scales.width = MAX(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case BranchFacilityIconResizingBehaviorStretch:
            break;
        case BranchFacilityIconResizingBehaviorCenter:
        {
            scales.width = 1;
            scales.height = 1;
            break;
        }
    }
    
    CGRect result = CGRectStandardize(rect);
    result.size.width *= scales.width;
    result.size.height *= scales.height;
    result.origin.x = target.origin.x + (target.size.width - result.size.width) / 2;
    result.origin.y = target.origin.y + (target.size.height - result.size.height) / 2;
    return result;
}
