//
//  BranchFacilityIcon.h
//  auroraride
//
//  Created by liasica on 2023/12/29.
//  Copyright © 2023 auroraride. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>

static CGSize const DESIGISIZE = {90, 104};

typedef NSString *BranchFacilityType NS_STRING_ENUM;

FOUNDATION_EXPORT BranchFacilityType const BranchFacilityTypeStore;
FOUNDATION_EXPORT BranchFacilityType const BranchFacilityTypeRest;
FOUNDATION_EXPORT BranchFacilityType const BranchFacilityTypeV72;
FOUNDATION_EXPORT BranchFacilityType const BranchFacilityTypeV60;

typedef NS_ENUM(NSInteger, BranchFacilityIconResizingBehavior)
{
    BranchFacilityIconResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    BranchFacilityIconResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    BranchFacilityIconResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    BranchFacilityIconResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect BranchFacilityIconResizingBehaviorApply(BranchFacilityIconResizingBehavior behavior, CGRect rect, CGRect target);


@interface BranchFacilityIcon : NSObject

// Drawing Methods
+ (UIImage *) draw:(int)number scale:(double)scale branchFacilityType:(NSString *)branchFacilityType color:(NSString *)color;

// 绘制网点设施
+ (void)drawBranchFacilityIconWithFrame: (CGRect)targetFrame number:(int)number branchFacilityType:(NSString *)branchFacilityType resizing: (BranchFacilityIconResizingBehavior)resizing iconColor:(UIColor *)iconColor;

// HEX 转为 UIColor
+ (UIColor *)UIColorFromHexString:(NSString *)hexString;

@end
